name: Compile TWRP

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
  
    container: 
      image: zycromerz/kerneldocker:v2

    steps:
    - uses: actions/checkout@v2
    - name: Compile GCC
      run: |
        chmod +x do-now.sh
        ./do-now.sh